<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="198254" started-at="2018-04-09T14:48:01Z" finished-at="2018-04-09T14:51:19Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="198254" started-at="2018-04-09T14:48:01Z" finished-at="2018-04-09T14:51:19Z">
      <class name="fwupdate">
        <test-method status="PASS" signature="setup()[pri:0, instance:fwupdate@3c0ecd4b]" name="setup" is-config="true" duration-ms="748" started-at="2018-04-09T20:18:01Z" finished-at="2018-04-09T20:18:02Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="newTest()[pri:0, instance:fwupdate@3c0ecd4b]" name="newTest" duration-ms="197476" started-at="2018-04-09T20:18:02Z" finished-at="2018-04-09T20:21:19Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Machine is already updated to latest FW version 1.18.7]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Machine is already updated to latest FW version 1.18.7
	at org.testng.Assert.fail(Assert.java:93)
	at fwupdate.newTest(fwupdate.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- newTest -->
      </class> <!-- fwupdate -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
